spring:
    profiles:
        # 指定运行环境
#        java -jar project-name.jar --spring.profiles.active=pro
        active: default
#    logging:
#        config: src/main/resources/log4j2.xml
    application:
        name: geometry
    datasource: 
        url: jdbc:h2:file:~/localH2
        driverClassName: org.h2.Driver
        username: sa
        password: 
        platform: h2
    data:
        mongodb:
            uri: mongodb://10.20.11.249:27017/geometry
#    redis:
#        host: 192.168.99.100
#        port: 6379
#        database: 1
         
# Tomcat配置
server:
    servlet: 
        context-path: /
    port: 50680